# model settings
model:
    type: 'CoDETR'
    backbone:
        type: 'ResNet'
        depth: 50
        out_layers: ["res2", "res3", "res4", "res5"]
        frozen_stages: 1
        norm: 'FrozenBN'
    neck:
        type: 'ChannelMapper'
        input_channels: {"res2": 256, "res3": 512, "res4": 1024, "res5": 2048}
        in_features: ["res2", "res3", "res4", "res5"]
        kernel_size: 1
        bias: False
        out_channels: 256
        num_outs: 5
        norm: 'GN'
    query_head:
        type: 'CoDINOHead'
        embed_dim: 256
        num_queries: 900
        num_classes: 80
        transformer:
            type: 'CoDinoTransformer'
            num_feature_levels: 5
            encoder:
                type: 'DINOTransformerEncoder'
                num_layers: 6
                embed_dim: 256
                num_feature_levels: 5
                attn_dropout: 0.0
                feedforward_dim: 2048
                ffn_dropout: 0.0
            decoder:
                type: 'DINOTransformerDecoder'
                num_layers: 6
                embed_dim: 256
                num_feature_levels: 5
                return_intermediate: True
                attn_dropout: 0.0
                feedforward_dim: 2048
                ffn_dropout: 0.0
        position_embedding:
            type: 'PositionEmbeddingSine'
            num_pos_feats: 128
            temperature: 20
            normalize: True
        criterion:
            type: 'DINOCriterion'
            num_classes: 80
            matcher:
                type: 'HungarianAssigner'
                cost_class: 2.0
                cost_bbox: 5.0
                cost_giou: 2.0
                cost_class_type: 'focal_loss_cost'
                alpha: 0.25
                gamma: 2.0
            weight_dict:
                loss_class: 1
                loss_bbox: 5.0
                loss_giou: 2.0
                loss_class_dn: 1
                loss_bbox_dn: 5.0
                loss_giou_dn: 2.0
            loss_class_type: 'focal_loss'
            alpha: 0.25
            gamma: 2.0
            two_stage_binary_cls: False
            num_dn: 100
test_cfg:
    nms_type: 'soft_nms'
    iou_threshold: 0.8
