# model settings
model:
    type: 'CoDETR'
    backbone:
        type: 'SwinTransformer'
        batch_size: 1
        img_size: [1536, 1536]
        embed_dim: 192
        depths: [2, 2, 18, 2]
        num_heads: [6, 12, 24, 48]
        out_indices: [0, 1, 2, 3]
        window_size: 12
        ape: False
        drop_path_rate: 0.3
        patch_norm: True
    neck:
        type: 'ChannelMapper'
        input_channels: {"res2": 192, "res3": 384, "res4": 768, "res5": 1536}
        in_features: ["res2", "res3", "res4", "res5"]
        kernel_size: 1
        bias: False
        out_channels: 256
        num_outs: 5
        norm: 'GN'
    query_head:
        type: 'CoDINOHead'
        embed_dim: 256
        num_queries: 900
        num_classes: 80
        num_dn: 500
        label_noise_ratio: 0.5
        box_noise_scale: 0.4
        transformer:
            type: 'CoDinoTransformer'
            num_feature_levels: 5
            encoder:
                type: 'DINOTransformerEncoder'
                num_layers: 6
                embed_dim: 256
                num_feature_levels: 5
                attn_dropout: 0.0
                feedforward_dim: 2048
                ffn_dropout: 0.0
            decoder:
                type: 'DINOTransformerDecoder'
                num_layers: 6
                embed_dim: 256
                num_feature_levels: 5
                return_intermediate: True
                attn_dropout: 0.0
                feedforward_dim: 2048
                ffn_dropout: 0.0
        position_embedding:
            type: 'PositionEmbeddingSine'
            num_pos_feats: 128
            temperature: 20
            normalize: True
        criterion:
            type: 'DINOCriterion'
            num_classes: 80
            matcher:
                type: 'HungarianAssigner'
                cost_class: 2.0
                cost_bbox: 5.0
                cost_giou: 2.0
                cost_class_type: 'focal_loss_cost'
                alpha: 0.25
                gamma: 2.0
            weight_dict:
                loss_class: 1
                loss_bbox: 5.0
                loss_giou: 2.0
                loss_class_dn: 1
                loss_bbox_dn: 5.0
                loss_giou_dn: 2.0
            loss_class_type: 'focal_loss'
            alpha: 0.25
            gamma: 2.0
            two_stage_binary_cls: False
            num_dn: 100
    bbox_head:
        type: 'CoATSSHead'
        num_classes: 80
        in_channels: 256
        stacked_convs: 1
        feat_channels: 256
        anchor_generator:
            type: 'AnchorGenerator'
            ratios: [1.0]
            octave_base_scale: 8
            scales_per_octave: 1
            strides: [4, 8, 16, 32, 64, 128]
        bbox_coder:
            type: 'DeltaXYWHBBoxCoder'
            target_means: [.0, .0, .0, .0]
            target_stds: [0.1, 0.1, 0.2, 0.2]
        loss_cls:
            type: 'FocalLoss'
            use_sigmoid: True
            gamma: 2.0
            alpha: 0.25
            loss_weight: 12.0
        loss_bbox:
            type: 'GIoULoss'
            loss_weight: 24.0
        loss_centerness:
            type: 'CrossEntropyLoss'
            use_sigmoid: True
            loss_weight: 12.0
        assigner:
            type: 'ATSSAssigner'
            topk: 9
        train_cfg:
            allowed_border: -1
            pos_weight: -1.
test_cfg:
    nms_type: 'soft_nms'
    iou_threshold: 0.8
